/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, vcc */
/* Command for C compiler:
   vccexe.exe /c --platform:amd64 /nologo -DWIN32_LEAN_AND_MEAN /openmp /O2  /IC:\nim\lib /FoC:\Users\jaina18\Documents\simtest\nimcache\main.obj C:\Users\jaina18\Documents\simtest\nimcache\main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef linux
#undef near
typedef struct TY_1JlHotiCdrGmGQRjzmOgQg TY_1JlHotiCdrGmGQRjzmOgQg;
typedef struct TY_boJ9argmCD9bXSmLW89aEvVWA TY_boJ9argmCD9bXSmLW89aEvVWA;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TY_1JlHotiCdrGmGQRjzmOgQg {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
NF Field4;
NF Field5;
NF Field6;
NF Field7;
};

struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);

struct TNimType {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;

struct TNimNode {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);

struct Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};

struct GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};

struct CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];

struct IntSet_EZObFrE3NC9bIb3YMkY9crZA {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];

struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];

struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};

struct MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};

struct GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};

struct CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};

struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};

struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};

struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};

struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};

struct LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};

struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];

struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};

struct PageDesc_fublkgIY4LG3mT51LU2WHg {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};

struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_boJ9argmCD9bXSmLW89aEvVWA {
  TGenericSeq Sup;
  TY_1JlHotiCdrGmGQRjzmOgQg data[SEQ_DECL_SIZE];
};
N_NIMCALL(NF, ntepochTime)(void);
static N_NIMCALL(void, Marker_TY_boJ9argmCD9bXSmLW89aEvVWA)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(TY_boJ9argmCD9bXSmLW89aEvVWA*, split_9ba8xJiNoU9aHX7HmGZ68mGQ)(TY_1JlHotiCdrGmGQRjzmOgQg* s, NI spaces);
N_NIMCALL(TY_boJ9argmCD9bXSmLW89aEvVWA*, newSeq_t7ymgOjzhuSqFhEoTzkv8A)(NI len);
N_NIMCALL(NF, getSplitIntensityRatio_kURSCqblShcNexe4T9cvN7A)(TY_1JlHotiCdrGmGQRjzmOgQg* space, NF accuracy, NF numSections, NF sectionNum, NF height, NF width);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwmain)(NF* x, NF y);
N_NIMCALL(NF, exp1_GzHU3IlbBDrraj6XQWPqjA)(NF y);
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAw_2main)(NF* x, NF y);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(TY_1JlHotiCdrGmGQRjzmOgQg, recombine_47CuNFdfkBeDuYDZs2dAsQ)(TY_boJ9argmCD9bXSmLW89aEvVWA* spaces);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void);
N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
TY_1JlHotiCdrGmGQRjzmOgQg initialPulse_9bGgafXkXEVmojQfEeJBoiw;
NF time1_3dFZBfDyR5LCVb5lgcsuDg;
TY_boJ9argmCD9bXSmLW89aEvVWA* spaces_1Bhq9ac7p1SppWfT38rlBNg;
TNimType NTI_1JlHotiCdrGmGQRjzmOgQg_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_boJ9argmCD9bXSmLW89aEvVWA_;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* name_heOwHj0JR4YxDsRrTxFmkA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
NIM_CONST TY_1JlHotiCdrGmGQRjzmOgQg TM_V45tF8B8NBcxFcjfe7lhBw_2 = {1.0000000000000000e+002,
8.6599999999999994e+001,
5.0000000000000000e+001,
5.0000000000000000e+001,
8.6599999999999999e-001,
8.6599999999999999e-001,
1.0000000000000000e+002,
1.0000000000000000e+000}
;
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_5, "Took ", 5);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_6, " milliseconds", 13);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_7, "Push enter to continue...", 25);
static N_NIMCALL(void, Marker_TY_boJ9argmCD9bXSmLW89aEvVWA)(void* p, NI op) {
	TY_boJ9argmCD9bXSmLW89aEvVWA* a;
	NI T1_;
	a = (TY_boJ9argmCD9bXSmLW89aEvVWA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	}
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_4)(void) {
	nimGCvisit((void*)spaces_1Bhq9ac7p1SppWfT38rlBNg, 0);
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwmain)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAw_2main)(NF* x, NF y) {
	(*x) = ((NF)((*x)) * (NF)(y));
}

N_NIMCALL(NF, exp1_GzHU3IlbBDrraj6XQWPqjA)(NF y) {
	NF result;
	NF x;
{	result = (NF)0;
	x = y;
	x = ((NF)(1.0000000000000000e+000) + (NF)(((NF)(x) / (NF)(2.5600000000000000e+002))));
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&x), x);
	result = x;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NF, getSplitIntensityRatio_kURSCqblShcNexe4T9cvN7A)(TY_1JlHotiCdrGmGQRjzmOgQg* space, NF accuracy, NF numSections, NF sectionNum, NF height, NF width) {
	NF result;
	NF ySearchLB;
	NF ySearchUB;
	NF xSearchLB;
	NF xSearchUB;
	NF x;
	NF y;
	NF VzIntDistsq;
	NF hWidthsq;
	result = (NF)0;
	ySearchLB = ((NF)(((NF)(-5.8029999999999999e+000) * (NF)(height))) + (NF)(((NF)(((NF)(((NF)(((NF)(5.8029999999999999e+000) * (NF)(height))) * (NF)(2.0000000000000000e+000))) / (NF)(numSections))) * (NF)(((NF)(sectionNum) - (NF)(1.0000000000000000e+000))))));
	ySearchUB = ((NF)(((NF)(5.8029999999999999e+000) * (NF)(height))) - (NF)(((NF)(((NF)(((NF)(((NF)(5.8029999999999999e+000) * (NF)(height))) * (NF)(2.0000000000000000e+000))) / (NF)(numSections))) * (NF)(((NF)(numSections) - (NF)(sectionNum))))));
	xSearchLB = ((NF)(-5.8029999999999999e+000) * (NF)(width));
	xSearchUB = ((NF)(5.8029999999999999e+000) * (NF)(width));
	x = xSearchLB;
	y = ySearchLB;
	result = 0.0;
	VzIntDistsq = ((NF)((*space).Field2) * (NF)((*space).Field2));
	hWidthsq = ((NF)(width) * (NF)(width));
	{
		if (!(numSections == sectionNum)) goto LA3_;
		pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&ySearchUB), 1.0000000000000000e+000);
	}
	LA3_: ;
	{
		while (1) {
			if (!(y < ((NF)(ySearchUB) - (NF)(1.0000000000000000e-004)))) goto LA6;
			{
				while (1) {
					NF T9_;
					if (!(x < xSearchUB)) goto LA8;
					T9_ = (NF)0;
					T9_ = exp1_GzHU3IlbBDrraj6XQWPqjA(((NF)(((NF)(((NF)(((NF)(-1.0000000000000000e+000) * (NF)(x))) * (NF)(x))) / (NF)(((NF)(2.0000000000000000e+000) * (NF)(hWidthsq))))) - (NF)(((NF)(((NF)(((NF)(y) - (NF)(((NF)((*space).Field4) * (NF)(x))))) * (NF)(((NF)(y) - (NF)(((NF)((*space).Field4) * (NF)(x))))))) / (NF)(((NF)(2.0000000000000000e+000) * (NF)(VzIntDistsq)))))));
					pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&result), ((NF)(((NF)(((NF)(1.1200000000000000e+002) * (NF)(accuracy))) * (NF)(T9_))) / (NF)(((NF)(6.2831853071795862e+000) * (NF)(((NF)(hWidthsq) * (NF)(VzIntDistsq)))))));
					pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&x), 1.1200000000000000e+002);
				} LA8: ;
			}
			pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&y), accuracy);
			x = xSearchLB;
		} LA6: ;
	}
	stareq__7kHiltrvRlcg6wSYR3CxAw_2main((&result), 5.0000000000000000e+003);
	return result;
}

N_NIMCALL(TY_boJ9argmCD9bXSmLW89aEvVWA*, split_9ba8xJiNoU9aHX7HmGZ68mGQ)(TY_1JlHotiCdrGmGQRjzmOgQg* s, NI spaces) {
	TY_boJ9argmCD9bXSmLW89aEvVWA* result;
	NF spacesD;
	NI i;
	result = (TY_boJ9argmCD9bXSmLW89aEvVWA*)0;
	result = newSeq_t7ymgOjzhuSqFhEoTzkv8A(((NI) (spaces)));
	spacesD = ((NF)(1.0000000000000000e+000) / (NF)(((NF) (spaces))));
	#pragma omp parallel for 
for (i = ((NI) 0); i <= ((result ? result->Sup.len : 0) - 1); ++i)	{
		NF intensityRatio;
		intensityRatio = getSplitIntensityRatio_kURSCqblShcNexe4T9cvN7A(s, ((NF)(1.0050000000000000e+003) * (NF)(spacesD)), ((NF) (spaces)), ((NF) (i)), (*s).Field1, (*s).Field0);
		result->data[i].Field0 = ((NF)(((NF)((*s).Field1) / (NF)((*s).Field4))) * (NF)(spacesD));
		result->data[i].Field1 = ((NF)((*s).Field1) * (NF)(spacesD));
		result->data[i].Field2 = (*s).Field2;
		result->data[i].Field3 = (*s).Field3;
		result->data[i].Field4 = (*s).Field4;
		result->data[i].Field5 = (*s).Field5;
		result->data[i].Field6 = ((NF)((*s).Field6) * (NF)(intensityRatio));
		result->data[i].Field7 = intensityRatio;
	}
	return result;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_NIMCALL(TY_1JlHotiCdrGmGQRjzmOgQg, recombine_47CuNFdfkBeDuYDZs2dAsQ)(TY_boJ9argmCD9bXSmLW89aEvVWA* spaces) {
	TY_1JlHotiCdrGmGQRjzmOgQg result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field2 = spaces->data[((NI) 0)].Field2;
	result.Field3 = spaces->data[((NI) 0)].Field3;
	result.Field4 = spaces->data[((NI) 0)].Field4;
	result.Field5 = spaces->data[((NI) 0)].Field5;
	{
		TY_1JlHotiCdrGmGQRjzmOgQg s;
		NI i;
		NI L;
		memset((void*)(&s), 0, sizeof(s));
		i = ((NI) 0);
		L = (spaces ? spaces->Sup.len : 0);
		{
			while (1) {
				if (!(i < L)) goto LA3;
				s = spaces->data[i];
				pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&result.Field6), s.Field6);
				pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&result.Field7), s.Field7);
				i += ((NI) 1);
			} LA3: ;
		}
	}
	result.Field0 = ((NF)(spaces->data[((NI) 0)].Field0) * (NF)(((NF) ((spaces ? spaces->Sup.len : 0)))));
	result.Field1 = ((NF)(((NF)(spaces->data[((NI) 0)].Field1) * (NF)(((NF) ((spaces ? spaces->Sup.len : 0)))))) * (NF)(((NF)(1.0000000000000000e+000) / (NF)(result.Field4))));
	return result;
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void) {
	nimGCvisit((void*)name_heOwHj0JR4YxDsRrTxFmkA, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	mainDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	TY_1JlHotiCdrGmGQRjzmOgQg T1_;
	NimStringDesc* T2_;
	NF T3_;
	NimStringDesc* T4_;
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_4);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_8);
	initialPulse_9bGgafXkXEVmojQfEeJBoiw = TM_V45tF8B8NBcxFcjfe7lhBw_2;
	time1_3dFZBfDyR5LCVb5lgcsuDg = ntepochTime();
	asgnRefNoCycle((void**) (&spaces_1Bhq9ac7p1SppWfT38rlBNg), split_9ba8xJiNoU9aHX7HmGZ68mGQ((&initialPulse_9bGgafXkXEVmojQfEeJBoiw), ((NI) 1000000)));
	T1_ = recombine_47CuNFdfkBeDuYDZs2dAsQ(spaces_1Bhq9ac7p1SppWfT38rlBNg);
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr(T1_.Field6);
	printf("%s\015\012", T2_? (T2_)->data:"nil");
	fflush(stdout);
	T3_ = (NF)0;
	T3_ = ntepochTime();
	T4_ = (NimStringDesc*)0;
	T4_ = nimFloatToStr(((NF)(((NF)(T3_) - (NF)(time1_3dFZBfDyR5LCVb5lgcsuDg))) * (NF)(1.0000000000000000e+003)));
	printf("%s%s%s\015\012", ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_5)? (((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_5))->data:"nil", T4_? (T4_)->data:"nil", ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6)? (((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6))->data:"nil");
	fflush(stdout);
	printf("%s\015\012", ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_7)? (((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_7))->data:"nil");
	fflush(stdout);
	asgnRefNoCycle((void**) (&name_heOwHj0JR4YxDsRrTxFmkA), readLine_fPRnXwDTqtynUYGl4OixAg(stdin));
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
static TNimNode* TM_V45tF8B8NBcxFcjfe7lhBw_3[8];
static TNimNode TM_V45tF8B8NBcxFcjfe7lhBw_0[9];
NTI_1JlHotiCdrGmGQRjzmOgQg_.size = sizeof(TY_1JlHotiCdrGmGQRjzmOgQg);
NTI_1JlHotiCdrGmGQRjzmOgQg_.kind = 18;
NTI_1JlHotiCdrGmGQRjzmOgQg_.base = 0;
NTI_1JlHotiCdrGmGQRjzmOgQg_.flags = 3;
TM_V45tF8B8NBcxFcjfe7lhBw_3[0] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[1];
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field0);
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].name = "Field0";
TM_V45tF8B8NBcxFcjfe7lhBw_3[1] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[2];
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field1);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].name = "Field1";
TM_V45tF8B8NBcxFcjfe7lhBw_3[2] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[3];
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field2);
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].name = "Field2";
TM_V45tF8B8NBcxFcjfe7lhBw_3[3] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[4];
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field3);
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].name = "Field3";
TM_V45tF8B8NBcxFcjfe7lhBw_3[4] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[5];
TM_V45tF8B8NBcxFcjfe7lhBw_0[5].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[5].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field4);
TM_V45tF8B8NBcxFcjfe7lhBw_0[5].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[5].name = "Field4";
TM_V45tF8B8NBcxFcjfe7lhBw_3[5] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[6];
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field5);
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].name = "Field5";
TM_V45tF8B8NBcxFcjfe7lhBw_3[6] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[7];
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field6);
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].name = "Field6";
TM_V45tF8B8NBcxFcjfe7lhBw_3[7] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[8];
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].offset = offsetof(TY_1JlHotiCdrGmGQRjzmOgQg, Field7);
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].name = "Field7";
TM_V45tF8B8NBcxFcjfe7lhBw_0[0].len = 8; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].kind = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].sons = &TM_V45tF8B8NBcxFcjfe7lhBw_3[0];
NTI_1JlHotiCdrGmGQRjzmOgQg_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[0];
NTI_boJ9argmCD9bXSmLW89aEvVWA_.size = sizeof(TY_boJ9argmCD9bXSmLW89aEvVWA*);
NTI_boJ9argmCD9bXSmLW89aEvVWA_.kind = 24;
NTI_boJ9argmCD9bXSmLW89aEvVWA_.base = (&NTI_1JlHotiCdrGmGQRjzmOgQg_);
NTI_boJ9argmCD9bXSmLW89aEvVWA_.flags = 2;
NTI_boJ9argmCD9bXSmLW89aEvVWA_.marker = Marker_TY_boJ9argmCD9bXSmLW89aEvVWA;
}

